name: Update readme with latest updates
on:
  push:
    branches:
      - main
  # schedule:
  #   # Runs every day at 5PM UTC (19:00 EET)
  #   - cron: '0 17 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: teroyks/rss-to-readme@v1
        with:
          feed-url: https://github.com/teroyks/knowledge/commits/main.atom
          readme-section: feed
          max: 10
          template: "### [{{ title }}]({{ link }}) \n*{{ contentSnippet }}*\n\n"
